# Generated by Django 4.2.16 on 2024-09-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nome',
            new_name='username',
        ),
    ]
