# Generated by Django 4.2.16 on 2024-09-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='atribuir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quem', to='app.usuarios'),
        ),
    ]
