# Generated by Django 4.2.16 on 2024-09-09 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_tarefa_atribuir'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaForm',
            fields=[
                ('id_Tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em progresso', 'Em progresso'), ('Completado', 'Completado')], default='Pendente', max_length=20)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
